version: "3.1"

services:
  db:
    build:
      context: ../
      dockerfile: docker-compose/postgres/Dockerfile
    env_file:
      - postgres/.postgres.env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker-compose/app/Dockerfile
    entrypoint: /bin/bash docker-compose/app/app_entrypoint.sh
    env_file:
      - ../.env
    links:
      - db:db
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ../:/app

volumes:
  postgres:
