version: "3.1"

services:
  db_geonames:
    build:
      context: ../
      dockerfile: docker-compose/postgres/Dockerfile
    env_file:
      - postgres/.postgres.env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_geonames:/var/lib/postgresql/data
  app:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker-compose/app/Dockerfile
    env_file:
      - ../.env.example
    links:
      - db_geonames:db_geonames
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - db_geonames
    volumes:
      - ../:/app

volumes:
  postgres_geonames:
